# Generated by Django 2.2.3 on 2020-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_en', models.CharField(max_length=32)),
                ('attribute_en', models.CharField(default='', max_length=32)),
                ('event_sh', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
