# Generated by Django 2.2.3 on 2020-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_en',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_sh',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
