# Generated by Django 2.2.3 on 2020-08-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0002_auto_20200827_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
    ]
