# Generated by Django 2.2.3 on 2020-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myxmind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmind_file',
            name='file',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
